name: typuspocus
base: core20 
version: '1.0'
summary: A magician that needs to type spells to go through their particular adventure.
description: |
    You are a magician. There's an object over the table that you have to vanish. In order 
    to do it, you have to type a spell that appears onscreen. You better do it fast and 
    accurately, or else the audience will get bored. Winner of the team category in PyWeek 3.

grade: stable
confinement: strict

apps:
    typuspocus:
        command: bin/pulsify-alsa $SNAP/bin/typuspocus
        extensions: 
            - gnome-3-38
        plugs:
            - home            # so it can acess files under the user's home
            - audio-playback  # to play sounds
        environment:
            PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
            LD_LIBRARY_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio

parts:
    typuspocus:
        plugin: python
        source: .
        requirements: 
            - requirements.txt
        stage-packages:
            - libx11-6
            - libpulse0

    alsa-lib:
        plugin: autotools
        source: http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-lib/alsa-lib_1.1.3.orig.tar.bz2
        autotools-configure-parameters:
        - --prefix=/usr
        - --sysconfdir=/etc
        - --libexec=/usr/lib
        - --libdir=/usr/lib
        - --localstatedir=/var
        - --with-configdir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/share/alsa
        - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
        - --disable-static
        organize:
            snap/*/current/usr/lib/*: usr/lib/
        stage:
        - usr/include
        - usr/lib
        prime:
        - -usr/bin
        - -usr/include
        - -usr/lib/pkgconfig
        - -usr/share/alsa/alsa.conf
        - -usr/share/alsa/pcm
        - -usr/share/alsa/topology/broadwell

    alsa-plugins:
        after: [alsa-lib]
        plugin: autotools
        source: http://archive.ubuntu.com/ubuntu/pool/main/a/alsa-plugins/alsa-plugins_1.1.1.orig.tar.bz2
        autotools-configure-parameters:
        - --prefix=/usr
        - --sysconfdir=/etc
        - --libexec=/usr/lib
        - --libdir=/usr/lib
        - --localstatedir=/var
        - --disable-oss
        - --disable-usbstream
        - --disable-arcamav
        - --disable-avcodec
        - --with-plugindir=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/lib/alsa-lib
        - --disable-static
        organize:
          snap/*/current/usr/lib/*: usr/lib/
        stage:
        - usr/lib
        - usr/share/alsa
        build-packages:
        - libpulse-dev
        stage-packages:
        - libpulse0

    alsa:
        plugin: nil
        after: [alsa-plugins, alsa-lib]
        override-pull: |
            snapcraftctl pull
            cat > alsa.conf <<EOF
            pcm.!default {
              type pulse
              fallback "sysdefault"
              hint {
                show on
                description "Default ALSA Output (currently PulseAudio Sound Server)"
              }
            }
            ctl.!default {
              type pulse
              fallback "sysdefault"
            }
            EOF
            cat > pulsify-alsa <<EOF
            #!/bin/bash
            if [ "\$SNAP_ARCH" == "amd64" ]; then
              ARCH="amd64-linux-gnu"
            elif [ "\$SNAP_ARCH" == "armhf" ]; then
              ARCH="arm-linux-gnueabihf"
            elif [ "\$SNAP_ARCH" == "arm64" ]; then
              ARCH="aarch64-linux-gnu"
            else
              ARCH="\$SNAP_ARCH-linux-gnu"
            fi
            export LD_LIBRARY_PATH="\$SNAP/usr/lib/alsa-lib:\$SNAP/usr/lib/\$ARCH/pulseaudio:\$LD_LIBRARY_PATH"
            export ALSA_CONFIG_PATH="\$SNAP/etc/alsa.conf"
            exec "\$@"
            EOF
        override-build: |
            snapcraftctl build
            install -m644 -D -t $SNAPCRAFT_PART_INSTALL/etc alsa.conf
            install -m755 -D -t $SNAPCRAFT_PART_INSTALL/bin pulsify-alsa
